// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcHotelReservation.Data;

#nullable disable

namespace MvcHotelReservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241222185517_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MvcHotelReservation.Models.Chambre", b =>
                {
                    b.Property<int>("IdChambre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdChambre"));

                    b.Property<int?>("Capacite")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Disponibilite")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumeroChambre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrixParNuit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TypeChambre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdChambre");

                    b.ToTable("Chambres");
                });

            modelBuilder.Entity("MvcHotelReservation.Models.Paiement", b =>
                {
                    b.Property<int>("IdPaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaiement"));

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdReservation")
                        .HasColumnType("int");

                    b.Property<string>("MethodePaiement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ReservationIdReservation")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPaiement");

                    b.HasIndex("ReservationIdReservation");

                    b.ToTable("Paiements");
                });

            modelBuilder.Entity("MvcHotelReservation.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReservation"));

                    b.Property<int>("ChambreIdChambre")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdChambre")
                        .HasColumnType("int");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontantTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateuridUtilisateur")
                        .HasColumnType("int");

                    b.HasKey("IdReservation");

                    b.HasIndex("ChambreIdChambre");

                    b.HasIndex("UtilisateuridUtilisateur");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("MvcHotelReservation.Models.Utilisateur", b =>
                {
                    b.Property<int>("idUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUtilisateur"));

                    b.Property<DateTime>("dateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("motDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idUtilisateur");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MvcHotelReservation.Models.Paiement", b =>
                {
                    b.HasOne("MvcHotelReservation.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationIdReservation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("MvcHotelReservation.Models.Reservation", b =>
                {
                    b.HasOne("MvcHotelReservation.Models.Chambre", "Chambre")
                        .WithMany()
                        .HasForeignKey("ChambreIdChambre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MvcHotelReservation.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateuridUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambre");

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
