<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\Account\" />
    <Folder Include="Views\Chambre\" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\fonts\interstate-black-cond-58b642507872b.otf" />
    <_ContentIncludedByDefault Remove="wwwroot\fonts\interstate-thin-italic-58b641b2d5a92.otf" />
  </ItemGroup>

</Project>
